<?php
require("../../inc/connectdbs.pdo.php");

$sql = "SELECT * FROM dealer_mitsu ";
$res = PDO_CONNECTION::fourinsure_mitsu()->query($sql)->fetchAll(2);

foreach ($res as $array) {
    $password = randomPassword();
    $customer = "INSERT INTO tb_customer (
        nameuser,
        s_name,
        Cus_vat1,
        Cus_vat7,
        Cus_tax3,
        title_sub,
        sub,
        icard,
        `user`,
        pw,
        pwclaim,
        `address`,
        Dealer_code,
        Dealer_saka,
        Email,
        Email2,
        Email3,
        `location`,
        `Group`,
        cus_add,
        cus_group,
        cus_town,
        cus_lane,
        cus_road,
        cus_tumbon,
        cus_amphur,
        cus_province,
        cus_postal,
        Email4,
        Email5,
        Contact,
        Contact2,
        group_pv,
        saka,
        pay_tel,
        pay_contact,
        Email6,
        Email7,
        Email8,
        point_use,
        emp_namerenew,
        emp_telrenew,
        emp_faxrenew,
        emp_emailrenew,
        tll,
        group_mk,
        ID_EMP,
        manager_zone,
        manager_zone_tel,
        manager_branch,
        manager_branch_tel,
        mk_username,
        mk_tel,
        menu_prb,
        menu_red,
        menu_year,
        menu_new,
        emp_lastrenew,
        emp_titlerenew,
        myear_request,
        myear_date,
        mnew_request,
        mnew_date,
        claim,
        viewsale,
        bpactive,
        menu_stock,
        multibrand,
        status_use,
        region
    ) VALUES (
        'Mitsubishi',
        '1',
        '0',
        '0',
        '0',
        'บริษัท',
        '$array[namecompany]',
        '',
        '$array[dealercode]',
        '$password',
        '$password',
        '',
        '$array[dealercode]',
        '',
        '$array[email]',
        '',
        '',
        '',
        'Mitsubishi',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        '$array[address]',
        '',
        '',
        '',
        '$array[phone]',
        '$array[namedealer]',
        '',
        '',
        '',
        '0',
        '',
        '',
        '$array[fax]',
        '',
        '',
        '0',
        '',
        '',
        '',
        '',
        '',
        '',
        '',
        'Y',
        'Y',
        'Y',
        'Y',
        '',
        '',
        '',
        '2021-06-01 13:40:44',
        '',
        '0000-00-00 00:00:00',
        'DEALER',
        '',
        '',
        '',
        '',
        '',
        '$array[region]'
    )";

    PDO_CONNECTION::fourinsure_mitsu()->prepare($customer)->execute();
}


function randomPassword() {
	$alphabet = "abcdefghijklmnopqrstuwxyz0123456789";
	$pass = array();
	$alphaLength = strlen($alphabet) - 1;
	for ($i = 0; $i < 8; $i++) {
		$n = rand(0, $alphaLength);
		$pass[] = $alphabet[$n];
	}
	return implode($pass);
}
?>